# Generated by Django 4.2.13 on 2024-07-08 09:01

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_url', models.CharField(max_length=1024, verbose_name='Внешняя ссылка')),
                ('document', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='./media/docs'), upload_to='', verbose_name='Файл документа')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_question', models.BooleanField(default=True, verbose_name='Первый вопрос')),
                ('problem_type', models.CharField(choices=[('product', 'Product'), ('repair', 'Repair')], max_length=20, verbose_name='Тип проблемы')),
                ('question_wording', models.CharField(max_length=512, verbose_name='Формулировка вопроса')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_text', models.TextField(verbose_name='Краткое описание решения')),
                ('document_template', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='./media/doc_templates'), upload_to='', verbose_name='Шаблон документа')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('next_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_question', to='second_help.question')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='second_help.question')),
            ],
        ),
    ]
