# Generated by Django 4.2.13 on 2024-07-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_help', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='problem_type',
            field=models.CharField(choices=[('Товар', 'Товар'), ('Ремонт', 'Ремонт')], max_length=20, verbose_name='Тип проблемы'),
        ),
    ]
