# Generated by Django 4.2.13 on 2024-07-10 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second_help', '0002_alter_question_problem_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='first_question',
        ),
        migrations.AddField(
            model_name='question',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='second_help.solution', verbose_name='решение'),
        ),
    ]
