# Generated by Django 4.2.13 on 2024-07-14 09:19

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_help', '0006_remove_question_solution_answer_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='document',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='./media/articles'), upload_to='', verbose_name='Файл документа'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='web_url',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Внешняя ссылка'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='document_template',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='./media/doc_templates'), upload_to='', verbose_name='Шаблон документа'),
        ),
    ]
