# Generated by Django 4.2.13 on 2024-07-14 21:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second_help', '0007_alter_articles_document_alter_articles_web_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('average_score', models.IntegerField(verbose_name='Средняя оценка')),
                ('solution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scored_solution', to='second_help.solution', verbose_name='решение')),
            ],
        ),
    ]
