# Generated by Django 4.2.13 on 2024-07-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_help', '0009_tag_articles_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='name',
            field=models.CharField(default='default_name', max_length=25),
        ),
    ]
