# Generated by Django 4.2.13 on 2024-07-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_help', '0010_articles_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='name',
            field=models.CharField(default='default_name', max_length=125),
        ),
    ]
