# Generated by Django 4.2.13 on 2024-07-15 13:37

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_help', '0011_alter_articles_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='def_name', max_length=125)),
                ('document', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='./media/doc_templates'), upload_to='', verbose_name='Шаблон документа')),
                ('tags', models.ManyToManyField(to='second_help.tag')),
            ],
        ),
    ]
